name: Pow

on:
  schedule:
    - cron: "0 */4 * * *"
  workflow_dispatch:

jobs:
  live:
    runs-on: ubuntu-latest  
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Pow
        id: pow
        env:
          KEYPAIR: ${{ secrets.KEYPAIR }}
        run: |
          ./t.sh
          TIME=$(TZ=Asia/Shanghai date "+%Y-%m-%d %H:%M")
          echo "$TIME" | cat - time.log > temp && mv temp time.log
          {
            echo "MSG<<EOF" >> $GITHUB_OUTPUT
            if [ "$ONE_COUNT" -lt 250 ]; then
              echo "Pow success 🎉"
            else
              echo "Pow failed 😥"
            fi
            echo [$TIME]\(https://github.com/D0O0R/Learn-solana/actions/runs/${{ github.run_id }}\)
            echo "EOF"
          } >> $GITHUB_OUTPUT
      
      - name: Sent message
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_ID }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          format: markdown
          message: |
            ${{steps.ke5p.outputs.MSG}}
      
      - name: Commit
        run: |
          git config --global user.email D0OR@pm.me
          git config --global user.name D0O0R
          git add .
          git commit -m "live" -a
      
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}